# Generated by Django 2.2.24 on 2021-07-30 13:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_message', models.CharField(max_length=10000)),
                ('time_added', models.TimeField(default=datetime.datetime(2021, 7, 30, 13, 19, 49, 861913, tzinfo=utc))),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.MyBlogUser')),
            ],
        ),
    ]
