# Generated by Django 2.2.24 on 2021-07-30 17:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0012_auto_20210730_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessage',
            name='userid',
        ),
        migrations.AddField(
            model_name='usermessage',
            name='username',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='time_added',
            field=models.TimeField(default=datetime.datetime(2021, 7, 30, 17, 20, 42, 654171, tzinfo=utc)),
        ),
    ]
