# Generated by Django 2.2.24 on 2021-07-30 18:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0014_auto_20210730_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='text_message',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='time_added',
            field=models.TimeField(default=datetime.datetime(2021, 7, 30, 18, 52, 29, 354265, tzinfo=utc)),
        ),
    ]
