# Generated by Django 2.2.24 on 2021-07-31 05:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0019_auto_20210731_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 31, 5, 45, 55, 144737, tzinfo=utc)),
        ),
    ]
