# Generated by Django 2.2.24 on 2021-07-31 05:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0020_auto_20210731_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 31, 5, 53, 42, 192203, tzinfo=utc)),
        ),
    ]
