# Generated by Django 2.2.24 on 2021-07-31 07:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0022_auto_20210731_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='text_message',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 31, 7, 32, 26, 321820, tzinfo=utc)),
        ),
    ]
