# Generated by Django 2.2.24 on 2021-07-31 07:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0024_auto_20210731_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='text_message',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 31, 7, 39, 46, 830843, tzinfo=utc)),
        ),
    ]
